/*
* generated by Xtext
*/
package org.eclipse.ocl.xtext.oclstdlib.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class OCLstdlibAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/eclipse/ocl/xtext/oclstdlib/parser/antlr/internal/InternalOCLstdlib.tokens");
	}
}
