/*
* generated by Xtext
*/
package org.eclipse.ocl.xtext.base.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
public class BaseProposalProvider extends org.eclipse.ocl.xtext.base.ui.contentassist.AbstractBaseProposalProvider {

}
