/*
 * generated by Xtext
 */
package org.eclipse.ocl.xtext.base.serializer;

import org.eclipse.ocl.xtext.base.serializer.AbstractBaseSyntacticSequencer;

public class BaseSyntacticSequencer extends AbstractBaseSyntacticSequencer {
}
