/*
 * generated by Xtext
 */
package org.eclipse.ocl.xtext.base.serializer;

import org.eclipse.ocl.xtext.base.serializer.AbstractBaseSemanticSequencer;

public class BaseSemanticSequencer extends AbstractBaseSemanticSequencer {
}
