/*******************************************************************************
 * Copyright (c) 2015 Willink Transformations and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     E.D.Willink - initial API and implementation
 *******************************************************************************/
/*
 * generated by Xtext
 */
package org.eclipse.ocl.xtext.base.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BaseUiModule extends org.eclipse.ocl.xtext.base.ui.AbstractBaseUiModule
{
	public static final String PLUGIN_ID = "org.eclipse.ocl.xtext.base.ui";

	public BaseUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
