/*
 * generated by Xtext
 */
package org.eclipse.ocl.xtext.base.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BaseUiModule extends org.eclipse.ocl.xtext.base.ui.AbstractBaseUiModule {
	public BaseUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
