/*
 * generated by Xtext
 */
package org.eclipse.ocl.examples.xtext.base;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BaseRuntimeModule extends org.eclipse.ocl.examples.xtext.base.AbstractBaseRuntimeModule {

}
