/**
 * This file was copied and re-packaged automatically by
 *     org.eclipse.ocl.examples.build.GenerateAutoCSModels.mwe2
 * from 
 *     org.eclipse.qvtd.runtime/src/org/eclipse/qvtd/runtime/internal/cs2as/CS2ASTransformationExecutor.java
 *
 * Do not edit this file. 
 */
package org.eclipse.ocl.xtext.base.cs2as.tx;

import org.eclipse.jdt.annotation.NonNull;
import org.eclipse.ocl.pivot.utilities.EnvironmentFactory;
import org.eclipse.ocl.pivot.evaluation.tx.AbstractTransformationExecutor;

public class CS2ASTransformationExecutor extends AbstractTransformationExecutor {

	public CS2ASTransformationExecutor(@NonNull EnvironmentFactory environmentFactory,
			@NonNull Class<? extends CS2ASTransformer> txClass)
					throws ReflectiveOperationException {
		super(environmentFactory, txClass);
	}

	@Override
	public @NonNull CS2ASTransformer getTransformer() {
		return (CS2ASTransformer) super.getTransformer();
	}
}
